# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170331_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='attorney',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='case_type_detail',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='judge',
        ),
    ]
