# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userform_case_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
